### PR TITLE
Added co16353sidak to contributors list

### PR DESCRIPTION
**Pull request by theNaut1lus**
Fixes #issuenumber
-
Added co16353sidak to contributors list

### CODE REVIEW

**Review by arshadkazmi42 — CHANGES_REQUESTED** [review]
Can you generate the HOF using the rhof-cli tool.
And update the contributors list
`rhof --r=rhof-cli --u=arshadkazmi42`
you can use above command to generate after installing rhof-cli

**Comment by theNaut1lus** [comment]
@arshadkazmi42 
Let me do this one myself. I have understood the use-case now.

**Comment by arshadkazmi42** [comment]
> @arshadkazmi42
> Let me do this one myself. I have understood the use-case now.

Cool. Go ahead

**Comment by theNaut1lus** [comment]
Please check now @arshadkazmi42

**Review by arshadkazmi42 — APPROVED** [review]
Awesome :tada:

**Comment by arshadkazmi42** [comment]
Do give a star if you like these projects.

**Pull request merged**
